version: "3.9"  # optional since v1.27.0
services:
  zookeeper:
    image: library/zookeeper:3.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafkasvc:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stocks"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "nc -w 2 localhost 9092 || false"
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9092:9092"
      - "19092:19092"

  runner:
    image: runner
    environment:
      AA_GRAPHITE_ENABLED: "true"
      JAVA_XMS: 128m
    volumes:
      - ./configs/runner:/config
    depends_on:
      kafkasvc:
        condition: service_healthy